# Generated by Django 5.2.3 on 2025-07-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField(unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('km', models.IntegerField(verbose_name='Kilometres')),
                ('engine_size', models.IntegerField(verbose_name='Engine Size (cc)')),
                ('transmission', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo_link', models.URLField(verbose_name='Primary Photo URL')),
                ('description', models.TextField()),
                ('link', models.URLField(verbose_name='Detail Page on Richmonds')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
