# Generated by Django 5.2.4 on 2025-07-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km', models.PositiveIntegerField()),
                ('engine_size', models.CharField(max_length=100)),
                ('cylinders', models.PositiveIntegerField()),
                ('transmission', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='vehicle_images/')),
            ],
        ),
    ]
