# Generated by Django 5.2.3 on 2025-07-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='link',
            field=models.URLField(verbose_name='Vehicle page link on Richmonds'),
        ),
    ]
