# Generated by Django 5.2.4 on 2025-07-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='cylinders',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='engine_size',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='km',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='transmission',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
