# Generated by Django 5.2.3 on 2025-07-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_id',
        ),
    ]
