# Generated by Django 5.2.4 on 2025-07-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
    ]
