# Generated by Django 5.2.4 on 2025-07-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dob',
            field=models.DateField(),
        ),
    ]
