# Generated by Django 5.2.4 on 2025-07-31 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('booking_confirmed', 'Booking Confirmed'), ('booking_rescheduled', 'Booking Rescheduled'), ('booking_canceled', 'Booking Canceled'), ('staff_notification', 'Staff Notification')], max_length=30)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('sent_successfully', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='bookings.booking')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
