# Generated by Django 5.2.3 on 2025-08-11 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_emaillog'),
        ('vehicles', '0003_remove_vehicle_vehicle_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('user', 'requested_date', 'requested_time'), name='uniq_user_date_time'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('vehicle', 'requested_date', 'requested_time'), name='uniq_vehicle_timeslot'),
        ),
    ]
