# Generated by Django 5.2.3 on 2025-08-11 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_uniq_user_date_time_and_more'),
        ('vehicles', '0003_remove_vehicle_vehicle_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('guest_email', ''), _negated=True)), fields=('guest_email', 'requested_date', 'requested_time'), name='uniq_guest_email_date_time_if_no_user'),
        ),
    ]
