# Generated by Django 5.2.3 on 2025-08-14 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_uniq_guest_email_date_time_if_no_user'),
        ('vehicles', '0003_remove_vehicle_vehicle_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='uniq_user_date_time',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='uniq_vehicle_timeslot',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='uniq_guest_email_date_time_if_no_user',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'canceled'), _negated=True), fields=('user', 'requested_date', 'requested_time'), name='uniq_user_timeslot_active'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'canceled'), _negated=True), fields=('guest_name', 'guest_email', 'requested_date', 'requested_time'), name='uniq_guest_timeslot_active'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'canceled'), _negated=True), fields=('vehicle', 'requested_date', 'requested_time'), name='uniq_vehicle_timeslot_active'),
        ),
    ]
